version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14     # evita bugs de ZIP vazio em Node >=15
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Cleaning previous build artifacts..."
      - rm -rf .serverless .build
      - echo "Verifying Serverless Framework version..."
      - npx serverless --version

  build:
    commands:
      - echo "Packaging service without deployment..."
      - npx serverless package --stage cicd

      - echo "Inspecting package contents..."
      - ZIP_FILE=$(ls .serverless/*.zip | head -n1)
      - if [ -z "$ZIP_FILE" ]; then echo "❌ No zip artifact found"; exit 1; fi
      - echo "Found package: $ZIP_FILE"
      - unzip -l "$ZIP_FILE"

      - echo "Deploying service to AWS..."
      - mkdir -p .build
      - npx serverless deploy --stage cicd | tee .build/deploy.out

  post_build:
    commands:
      - echo "Running integration tests..."
      - npm run test:remote

artifacts:
  files:
    - .build/deploy.out
