version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: "14"
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Cleaning previous build artifacts..."
      - rm -rf .serverless .build
      - echo "Serverless Framework version:"
      - npx serverless --version

  build:
    commands:
      - echo "Packaging without deploy..."
      - npx serverless package --stage cicd

      - echo "Inspecting ZIP artifact..."
      - ZIP_FILE=$(ls .serverless/*.zip | head -n1)
      - if [ -z "$ZIP_FILE" ]; then echo "ERROR: No zip artifact found"; exit 1; fi
      - echo "Found package: $ZIP_FILE"
      - unzip -l "$ZIP_FILE"

      - echo "Deploying service..."
      - mkdir -p .build
      - npx serverless deploy --stage cicd | tee .build/deploy.out

  post_build:
    commands:
      - echo "Fetching API endpoint from CloudFormation..."
      - bash helpers/endpoint.sh                   # força execução em Bash
      - echo "Exporting TODOS_ENDPOINT..."
      - export TODOS_ENDPOINT                      # já definido dentro do endpoint.sh
      - echo "TODOS_ENDPOINT=$TODOS_ENDPOINT"
      - echo "Running integration tests..."
      - npm run test:remote

artifacts:
  files:
    - .build/deploy.out
