version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: "14"
    commands:
      - npm install

  pre_build:
    commands:
      - rm -rf .serverless .build
      - npx serverless --version

  build:
    commands:
      - npx serverless package --stage cicd
      - ZIP_FILE=$(ls .serverless/*.zip | head -n1)
      - if [ -z "$ZIP_FILE" ]; then echo "No zip artifact found"; exit 1; fi
      - unzip -l "$ZIP_FILE"
      - mkdir -p .build
      - npx serverless deploy --stage cicd | tee .build/deploy.out

  post_build:
    commands:
      - npm run test:remote

artifacts:
  files:
    - .build/deploy.out
