version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Cleaning previous artifacts..."
      - rm -rf .serverless .build
      - echo "Serverless Framework version:"
      - npx serverless --version

  build:
    commands:
      - echo "Packaging service..."
      - npx serverless package --stage cicd
      - echo "Locating ZIP artifact..."
      - ZIP_FILE=$(ls .serverless/*.zip | head -n1)
      - if [ -z "$ZIP_FILE" ]; then echo "No zip artifact found"; exit 1; fi
      - echo "Found $ZIP_FILE"
      - unzip -l "$ZIP_FILE"
      - echo "Deploying service..."
      - mkdir -p .build
      - npx serverless deploy --stage cicd | tee .build/deploy.out

  post_build:
    commands:
      - echo "Running integration tests... Tams"
###      - bash -lc "npm run test:remote"

artifacts:
  files:
    - .build/deploy.out
