version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14     # pin to Node.js 14
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Cleaning up artifacts..."
      - rm -rf .serverless .build
      - echo "Serverless version:"
      - npx serverless --version

  build:
    commands:
      - echo "Packaging without deploy..."
      - npx serverless package --stage cicd
      - echo "Inspecting ZIP contents..."
      - unzip -l .serverless/serverless-todo-cicd-cicd.zip
      - echo "Deploying to AWS..."
      - npx serverless deploy --stage cicd | tee .build/deploy.out

  post_build:
    commands:
      - echo "Running integration tests..."
      - ./test.sh

artifacts:
  files:
    - .build/deploy.out
